### ISSUE TITLE
I want to know how it works... but it doesn't :(

### ISSUE THREAD

**Issue by victorhom19** [mr-exception/rubix-cube-GA#1]
Hello! I'm russian student. Recently I have read your article about rubick's cube solver implementation. I tried to create my own solver using information that you presented in the article, but something went wrong. In a nutshell, I just repeated your steps of implementing solver but it didn't work. So then I went to your github repository and found that your implementation of solver in code differs from your implementation in article. I was surprised that you are not using neither filters which you greatley described in article. I also noticed that while running tests they are trying to solve cube which is already solved. In addition, your realization of crossover proccess strongly differs from what you showed in your article. So I managed to roll somehow  this cube and run tests again. In this case, your program still worked, but not in all cases. Also, iterating through tests took much longer time. To sum up, I'm very grateful for your article and code implemetation, but I want to know how to improve this solver. I would be glad if you answer my message d-(^.^)z

**Comment by mr-exception** [comment]
hi victor. I'm really happy you tried my solution in solving rubick's cube. actully that article is a little different from what i tried in this repo. filters and cross over steps in this repo are older than what i tried in that rubick's cube. and what made me to finish this research was a bug (I call it the spirit of GA). I you want, you can share your code with me (if it's python, java or js so I can understand it) and I try to help you. my mail address is darbandi1996@mail.com and my id in telegram is @reza_ddr
feel free to message me. I'll do my best :)

**Comment by victorhom19** [comment]
Greetings, did you recieved my email message?

**Comment by mr-exception** [comment]
hi. no I didn't recieved anything. what's your email address?

**Comment by victorhom19** [comment]
Well, I guess that's because of bug of mail servers. I'll try to use victorhome312@gmail.com to communicate with you. So, here I duplicate message I sent: "Greetings, Mr. Darbandi! I appreciate that you answered me. I really hope to end my project by creating a working solver, so it would be great if you help me. Here is a link to my [repo](https://github.com/victorhom19/CubeSolver). Count on you."

**Comment by mr-exception** [comment]
thank you. I'll take a look at your repository and try to understand the problem. I'll tell you when I'm finished
